### ISSUE TITLE
Add support for last_insterted_id

### ISSUE THREAD

**Issue by iamsergii** [bolav/fuse-sqlite#10]
in the definition file there is sqlite3_last_insert_rowid function listed, but when I try to use it I get 
`Uncaught ReferenceError: sqlite3_last_insert_rowid is not defined in Fuse.Scripting.ScriptModule+RequireContext`.

Am I supposed to track id manually?

**Comment by bolav** [comment]
This feature is not implemented yet. Feel free to add a PR. Which definition file are you talking about?
