### ISSUE TITLE
Error when installing via fusepm: "Found 0 unoproj files. Wanted 1"

### ISSUE THREAD

**Issue by tedekeroth** [bolav/fuse-sqlite#11]
When I did the fusepm install command, I got an error:

![image](https://cloud.githubusercontent.com/assets/10088477/19628263/32f23e3e-995a-11e6-8959-09d154c752ae.png)

I just installed fusepm and now tried as can be seen above. Running Win7 64bit.

**Comment by bolav** [comment]
You need to run fusepm in a directory with a fuse project.
