### ISSUE TITLE
up to date

### ISSUE THREAD

**Issue by skateBerlin** [bolav/fuse-sqlite#6]
Hi,

is this up to date? I am having a build fail. even while testing the master.
Sorry for asking, I am new to this. Maybe I am wrong. But if the master is not working, how can we dive into it to learn? 

Thank you!

**Comment by bolav** [comment]
Please tell me the fail, and how you are testing, and the version of fuse.

**Comment by skateBerlin** [comment]
Hi, I answered you in the slack community. 

I am on OSX 10.11
I am using fuse 0.12.2

build from terminal:
fuse preview sqlite_example.unoproj

error:  ... /SQLiteStatement.uno(6,8,6,13): Error E3114: There is nothing named 'Bolav' accessible in this scope. Are you missing a package reference?

Thank you for your quick response!

**Comment by bolav** [comment]
You need to install this library to use it. https://github.com/bolav/fuse-foreignhelpers

You can do it with `fusepm` like this: `fusepm install` in the SQLite directory.
