### ISSUE TITLE
Unable to install using fusepm

### ISSUE THREAD

**Issue by m1kr0b1** [bolav/fuse-sqlite#8]
Getting the following error when trying to install:

```
fusepm install https://github.com/bolav/fuse-sqlite
Found 2 unoproj files. Wanted 1
```

Any ideas?

**Comment by bolav** [comment]
You have 2 unoproj files in your current directory. Choose which one is the one you want to use by fusepm install https://github.com/bolav/fuse-sqlite --unoproj main.unoproj

**Comment by m1kr0b1** [comment]
Now something different is happening?

fusepm install https://github.com/bolav/fuse-sqlite --unoproj main.unoproj
Found 0 unoproj files. Wanted 1

**Comment by bolav** [comment]
I'm unclear on what you are trying to achieve? Are you trying to make the example work, or to install fuse-sqlite into one of your projects?

**Comment by m1kr0b1** [comment]
I'm just trying to install it in one of my projects, but it does not work?
Please excuse me if i'm a total noob...

**Comment by bolav** [comment]
If you write `fusepm install https://github.com/bolav/fuse-sqlite` in your projects directory it should be ready to use.

**Comment by m1kr0b1** [comment]
I do that, but this happens:

fusepm install https://github.com/bolav/fuse-sqlite

Found 2 unoproj files. Wanted 1

**Comment by bolav** [comment]
That error message states that you have 2 `.unoproj` files in the current directory.

**Comment by m1kr0b1** [comment]
Ooook, so the error is on my side, i presumed it was on the github side...
Many many apologies....
